services:
  serve-model:
    image: ghcr.io/release-engineering-group-13/model-service:latest 
    ports:
      - 8080:8080
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


  frontend:
    image: ghcr.io/release-engineering-group-13/app/frontend:latest
    ports:
      - "5000:80"
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      API_URL: "http://host.docker.internal:8081"

  backend: 
    image: ghcr.io/release-engineering-group-13/app/backend:latest
    ports:
      - 8081:8081
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend
    environment:
      MODEL_SERVICE_URL: "http://host.docker.internal:8080"

networks:
  default-network:
    driver: bridge