{
 "title": "Phishing",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Number of index requests ",
   "type": "timeseries",
   "description": "Showcases total number of requests to index page",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(num_index_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of prediction requests",
   "type": "timeseries",
   "description": "Total number of prediction requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(num_prediction_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Averrage prediction time",
   "type": "timeseries",
   "description": "Average time itaken to get a prediction",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "avg(prediction_time_sum)", "legendFormat": "__auto" }
   ]
  }
 ]
}