apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-depl
  labels:
    app: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model-service
        image: ghcr.io/release-engineering-group-13/model-service:{{.Values.model_service.version }}
        ports:
        - containerPort: {{.Values.model_service.port }}
        volumeMounts:
        - name: model-volume
          mountPath: /root/model
      volumes:
      - name: model-volume
        hostPath:
          path: /model  # Not sure if correct path
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-service
  ports:
  - port: {{.Values.model_service.port }}
    targetPort: {{.Values.model_service.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/release-engineering-group-13/app/frontend:{{.Values.frontend.version }}
        ports:
        - containerPort: {{.Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: {{.Values.frontend.port }}
    targetPort: {{.Values.frontend.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/release-engineering-group-13/app/backend:{{.Values.backend.version }}
        ports:
        - containerPort: {{.Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: {{.Values.backend.port }}
    targetPort: {{.Values.backend.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /model
        pathType: Prefix
        backend:
          service:
            name: model-service
            port:
              number: {{.Values.model_service.port }}
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: {{.Values.frontend.port }}
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: {{.Values.backend.port }}

