# playbookController.yml
---
- hosts: controller
  name: Initialize Master Node
  become: yes
  tasks:
  
    - name: remove swap
      shell: "swapoff -a"

    - name: Initialize Kubernetes Cluster
      shell: "kubeadm init --apiserver-advertise-address 192.168.56.10 --control-plane-endpoint 192.168.56.10 --pod-network-cidr=10.244.0.0/16"

    - name: Ensure $HOME/.kube directory exists
      file:
        path: $HOME/.kube
        state: directory
    
    - name: Copy kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: Change kubeconfig file permission
      file:
        path: $HOME/.kube/config 
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"

    - name: Install pod network
      shell: "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"

    # - name: Install Helm if it does not exist yet
    #   unarchive:
    #     src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
    #     dest: /usr/local/bin
    #     extra_opts: "--strip-components=1"
    #     mode: 0755
    #     remote_src: true
    #   args:
    #     creates: /usr/local/bin/helm