# playbookWorkers.yml
---
- hosts: controller
  name: Get Cluster Join Command
  become: yes 
  gather_facts: no
  tasks:

    - name: Create join command
      shell: "sudo kubeadm token create --print-join-command"
      register: join_command_raw

    - name: Set join command as variable
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"



- hosts: workers
  name: Initialize Worker Nodes
  become: yes
  gather_facts: no
  tasks:

    - name: Remove swap
      shell: "swapoff -a"

    - name: Join cluster
      shell: "sudo {{ hostvars[groups['controller'][0]].join_command }}"